image: alpine/edge
packages:
  - podman
  - ko
  - go # XXX: why not dep from ko?
secrets:
  - d45b9b20-bc8b-480e-8e6e-edb5e0fd5848 # containers auth
environment:
  KO_DOCKER_REPO: ghcr.io/xdavidwu/listables
tasks:
  - setup: |
      sudo rc-service cgroups start
      sudo modprobe tun
      sudo chmod o+rw /dev/net/tun
      echo build:100000:65536 | sudo tee /etc/subuid
      echo build:100000:65536 | sudo tee /etc/subgid
  - publish-base: |
      podman build -f listables/Containerfile.base -t ghcr.io/xdavidwu/listables/base:latest
      podman push ghcr.io/xdavidwu/listables/base:latest
  - publish: |
      
      cd listables
      # XXX github.com/google/go-containerregistry/pkg/authn does not search for this yet
      env REGISTRY_AUTH_FILE=~/.config/containers/auth.json \
        KO_DEFAULTBASEIMAGE=ghcr.io/xdavidwu/listables/base:latest \
        ko publish --bare .
